console.log("hello");
console.log("hello");

try{
    console.log(a);
} catch{
    console.log("caught an error ... a is not defined");
    // console.log(b);
}

console.log("hello after error");
console.log("hello after error");
console.log("hello after error");